-- Wellness tips: 7 per week, generated by Edge Function, served one per day
create table wellness_tips (
  id uuid primary key default gen_random_uuid(),
  day_of_week int not null check (day_of_week between 0 and 6),  -- 0=Sun...6=Sat
  week_start date not null,
  tip text not null,
  emoji text not null,
  created_at timestamptz default now()
);

create index idx_tips_week on wellness_tips(week_start, day_of_week);

-- Allow all authenticated users to read tips
alter table wellness_tips enable row level security;
create policy "Anyone can read tips" on wellness_tips for select using (true);
