// Human-readable names for all emojis in our picker
const EMOJI_NAMES: Record<string, string> = {
  // Smileys
  "😀": "Grinning", "😃": "Smiley", "😄": "Grin", "😁": "Beaming", "😆": "Laughing",
  "🤣": "ROFL", "😂": "Joy", "🙂": "Smile", "😊": "Blush", "😇": "Angel",
  "🥰": "Love Face", "😍": "Heart Eyes", "🤩": "Star Struck", "😘": "Kiss",
  "😗": "Kissing", "😚": "Kiss Blush", "😙": "Kiss Smile", "🥲": "Happy Tear",
  "😋": "Yum", "😛": "Tongue", "😜": "Wink Tongue", "🤪": "Zany", "😝": "Squint Tongue",
  "🤑": "Money Face", "🤗": "Hug", "🤭": "Giggle", "🫢": "Shh", "🫣": "Peeking",
  "🤫": "Quiet", "🤔": "Thinking", "🫡": "Salute", "🤐": "Zip", "🤨": "Raised Brow",
  "😐": "Neutral", "😑": "Blank", "😶": "No Mouth", "🫥": "Dotted Face",
  "😏": "Smirk", "😒": "Unamused", "🙄": "Eye Roll", "😬": "Grimace", "🤥": "Pinocchio",
  "🫨": "Shaking", "😌": "Relieved", "😔": "Pensive", "😪": "Sleepy", "🤤": "Drool",
  "😴": "Sleeping", "😷": "Mask", "🤒": "Sick", "🤕": "Bandage", "🤢": "Nauseous",
  "🤮": "Vomit", "🥵": "Hot", "🥶": "Cold", "🥴": "Woozy", "😵": "Dizzy",
  "🤯": "Mind Blown", "🤠": "Cowboy", "🥳": "Party", "🥸": "Disguised",
  "😎": "Cool", "🤓": "Nerd", "🧐": "Monocle", "😕": "Confused", "🫤": "Diagonal",
  "😟": "Worried", "🙁": "Frowning", "😮": "Open Mouth", "😯": "Hushed",
  "😲": "Astonished", "😳": "Flushed", "🥺": "Pleading", "🥹": "Holding Tears",
  "😦": "Frowning Open", "😧": "Anguished", "😨": "Fearful", "😰": "Anxious",
  "😥": "Sad Relief", "😢": "Crying", "😭": "Sobbing", "😱": "Scream",
  "😖": "Confounded", "😣": "Persevere", "😞": "Disappointed", "😓": "Downcast",
  "😩": "Weary", "😫": "Tired", "🥱": "Yawning", "😤": "Huffing",
  "😡": "Pouting", "😠": "Angry", "🤬": "Swearing", "😈": "Devil Smile",
  "👿": "Angry Devil", "💀": "Skull", "☠️": "Crossbones", "💩": "Poop", "🤡": "Clown",
  "👹": "Ogre", "👺": "Goblin", "👻": "Ghost", "👽": "Alien", "👾": "Space Invader",
  "🤖": "Robot", "😺": "Cat Smile", "😸": "Cat Grin", "😹": "Cat Joy",
  "😻": "Cat Hearts", "😼": "Cat Smirk", "😽": "Cat Kiss", "🙀": "Cat Weary",
  "😿": "Cat Cry", "😾": "Cat Pout", "🙈": "See No Evil", "🙉": "Hear No Evil",
  "🙊": "Speak No Evil",

  // Hands
  "👋": "Wave", "🤚": "Raised Hand", "🖐️": "Open Hand", "✋": "High Five",
  "🖖": "Vulcan", "🫱": "Right Hand", "🫲": "Left Hand", "🫳": "Palm Down",
  "🫴": "Palm Up", "🫷": "Push Left", "🫸": "Push Right", "👌": "OK",
  "🤌": "Pinched", "🤏": "Pinch", "✌️": "Peace", "🤞": "Crossed Fingers",
  "🫰": "Love You", "🤟": "Rock On", "🤘": "Horns", "🤙": "Call Me",
  "👈": "Left", "👉": "Right", "👆": "Up", "🖕": "Middle Finger", "👇": "Down",
  "☝️": "Point Up", "🫵": "Point at You", "👍": "Thumbs Up", "👎": "Thumbs Down",
  "✊": "Fist", "👊": "Fist Bump", "🤛": "Left Fist", "🤜": "Right Fist",
  "👏": "Clap", "🙌": "Raise Roof", "🫶": "Heart Hands", "👐": "Open Hands",
  "🤲": "Palms Up", "🤝": "Handshake", "🙏": "Pray",
  "✍️": "Writing", "💅": "Nail Polish", "🤳": "Selfie", "💪": "Flex",
  "🦾": "Mech Arm", "🦿": "Mech Leg", "👀": "Eyes", "👁️": "Eye",
  "👅": "Tongue", "👄": "Lips",

  // People
  "👶": "Baby", "🧒": "Child", "👦": "Boy", "👧": "Girl", "🧑": "Person",
  "👱": "Blond", "👨": "Man", "🧔": "Bearded", "👩": "Woman", "🧓": "Elder",
  "🙍": "Frowning", "🙎": "Pouting", "🙅": "No Good", "🙆": "OK Person",
  "💁": "Sassy", "🙋": "Raising Hand", "🤦": "Facepalm", "🤷": "Shrug",
  "👮": "Police", "🕵️": "Detective", "💂": "Guard", "🥷": "Ninja", "👷": "Builder",
  "🤴": "Prince", "👸": "Princess", "🤵": "Tuxedo", "👰": "Bride",
  "🤰": "Pregnant", "🤱": "Nursing", "👼": "Baby Angel", "🎅": "Santa",
  "🤶": "Mrs. Claus", "🦸": "Superhero", "🦹": "Supervillain", "🧙": "Wizard",
  "🧚": "Fairy", "🧛": "Vampire", "🧜": "Merperson", "🧝": "Elf",
  "💃": "Dancer", "🕺": "Disco", "🧖": "Spa", "🧗": "Climbing",
  "🤸": "Cartwheel", "🏋️": "Weightlifter", "🚴": "Cycling", "🏄": "Surfing",
  "🏊": "Swimming", "🧘": "Meditation",

  // Nature
  "🐶": "Dog", "🐱": "Cat", "🐭": "Mouse", "🐹": "Hamster", "🐰": "Bunny",
  "🦊": "Fox", "🐻": "Bear", "🐼": "Panda", "🐨": "Koala", "🐯": "Tiger",
  "🦁": "Lion", "🐮": "Cow", "🐷": "Pig", "🐸": "Frog", "🐵": "Monkey",
  "🐔": "Chicken", "🐧": "Penguin", "🐦": "Bird", "🦆": "Duck", "🦅": "Eagle",
  "🦉": "Owl", "🐺": "Wolf", "🐴": "Horse", "🦄": "Unicorn", "🐝": "Bee",
  "🦋": "Butterfly", "🐌": "Snail", "🐞": "Ladybug", "🐢": "Turtle", "🐍": "Snake",
  "🐙": "Octopus", "🦑": "Squid", "🐬": "Dolphin", "🐳": "Whale", "🦈": "Shark",
  "🐊": "Crocodile", "🐘": "Elephant", "🦒": "Giraffe", "🐕": "Dog", "🐈": "Cat",
  "🦜": "Parrot", "🦢": "Swan", "🦩": "Flamingo", "🐇": "Rabbit", "🦥": "Sloth",
  "🌵": "Cactus", "🌲": "Evergreen", "🌳": "Tree", "🌴": "Palm Tree", "🌱": "Sprout",
  "🌿": "Herb", "☘️": "Shamrock", "🍀": "Four Leaf", "🪴": "Potted Plant",
  "🍄": "Mushroom", "💐": "Bouquet", "🌷": "Tulip", "🌹": "Rose", "🌺": "Hibiscus",
  "🌸": "Cherry Blossom", "🌼": "Blossom", "🌻": "Sunflower",
  "🌙": "Moon", "🌎": "Earth Americas", "🌍": "Earth Africa", "🌏": "Earth Asia",
  "💫": "Dizzy Star", "⭐": "Star", "🌟": "Glowing Star", "✨": "Sparkles",
  "⚡": "Lightning", "🔥": "Fire", "🌈": "Rainbow", "☀️": "Sun", "☁️": "Cloud",
  "❄️": "Snowflake", "💧": "Droplet", "🫧": "Bubbles", "🌊": "Wave",

  // Food
  "🍇": "Grapes", "🍉": "Watermelon", "🍊": "Tangerine", "🍋": "Lemon",
  "🍌": "Banana", "🍍": "Pineapple", "🥭": "Mango", "🍎": "Apple", "🍑": "Peach",
  "🍒": "Cherries", "🍓": "Strawberry", "🫐": "Blueberries", "🥝": "Kiwi",
  "🥑": "Avocado", "🌽": "Corn", "🌶️": "Hot Pepper", "🥦": "Broccoli",
  "🍞": "Bread", "🥐": "Croissant", "🥞": "Pancakes", "🧇": "Waffle",
  "🧀": "Cheese", "🍖": "Meat", "🍗": "Drumstick", "🥩": "Steak",
  "🍔": "Burger", "🍟": "Fries", "🍕": "Pizza", "🌭": "Hot Dog",
  "🥪": "Sandwich", "🌮": "Taco", "🌯": "Burrito", "🥙": "Pita",
  "🍳": "Egg", "🥘": "Paella", "🍲": "Stew", "🥗": "Salad",
  "🍿": "Popcorn", "🍱": "Bento", "🍜": "Ramen", "🍝": "Spaghetti",
  "🍣": "Sushi", "🍤": "Shrimp", "🥟": "Dumpling", "🍦": "Ice Cream",
  "🍩": "Donut", "🍪": "Cookie", "🎂": "Birthday Cake", "🍰": "Cake",
  "🧁": "Cupcake", "🍫": "Chocolate", "🍬": "Candy", "🍭": "Lollipop",
  "☕": "Coffee", "🫖": "Teapot", "🍵": "Tea", "🍾": "Champagne",
  "🍷": "Wine", "🍸": "Cocktail", "🍹": "Tropical Drink", "🍺": "Beer",
  "🍻": "Cheers", "🥂": "Clink", "🥤": "Cup & Straw", "🧋": "Boba",

  // Activities
  "⚽": "Soccer", "🏀": "Basketball", "🏈": "Football", "⚾": "Baseball",
  "🎾": "Tennis", "🏐": "Volleyball", "🎱": "Billiards", "🏓": "Ping Pong",
  "🏸": "Badminton", "🥊": "Boxing", "🥋": "Martial Arts", "🎽": "Running Shirt",
  "🛹": "Skateboard", "⛸️": "Ice Skate", "🎿": "Skiing", "🏂": "Snowboard",
  "🎯": "Bullseye", "🎮": "Gaming", "🕹️": "Joystick", "🎲": "Dice",
  "🧩": "Puzzle", "🎭": "Theater", "🎨": "Art", "🎼": "Music Score",
  "🎵": "Music Note", "🎶": "Music", "🎤": "Mic", "🎧": "Headphones",
  "🎷": "Saxophone", "🎸": "Guitar", "🎹": "Piano", "🎻": "Violin",
  "🥁": "Drums", "🎬": "Clapperboard", "🏆": "Trophy", "🥇": "Gold Medal",
  "🏅": "Medal",

  // Travel
  "🚗": "Car", "🚕": "Taxi", "🏎️": "Race Car", "🚲": "Bicycle",
  "✈️": "Airplane", "🛫": "Takeoff", "🚀": "Rocket", "🛸": "UFO",
  "🏠": "House", "🏢": "Office", "🏛️": "Courthouse", "⛪": "Church",
  "🏰": "Castle", "🗼": "Tokyo Tower", "🗽": "Liberty", "🏔️": "Mountain",
  "⛰️": "Peak", "🌋": "Volcano", "🏕️": "Camping", "🏖️": "Beach",
  "🏜️": "Desert", "🏝️": "Island", "🎡": "Ferris Wheel", "🎢": "Roller Coaster",
  "🗺️": "World Map", "🧭": "Compass", "🌐": "Globe", "🗿": "Moai",

  // Objects
  "📱": "Phone", "💻": "Laptop", "⌨️": "Keyboard", "🖥️": "Desktop",
  "📷": "Camera", "📸": "Flash Camera", "📺": "TV", "🎙️": "Studio Mic",
  "⏰": "Alarm", "💡": "Lightbulb", "🔦": "Flashlight", "💸": "Money Wings",
  "💰": "Money Bag", "💳": "Credit Card", "💎": "Gem", "🔧": "Wrench",
  "🔨": "Hammer", "⚙️": "Gear", "🔮": "Crystal Ball", "🧿": "Evil Eye",
  "💊": "Pill", "🧬": "DNA", "🧸": "Teddy Bear", "🎁": "Gift",
  "🎈": "Balloon", "🎀": "Ribbon", "🎉": "Party Popper", "🎊": "Confetti",
  "✉️": "Envelope", "💌": "Love Letter", "📦": "Package", "🔑": "Key", "🗝️": "Old Key",

  // Hearts & Symbols
  "❤️": "Red Heart", "🧡": "Orange Heart", "💛": "Yellow Heart", "💚": "Green Heart",
  "💙": "Blue Heart", "💜": "Purple Heart", "🖤": "Black Heart", "🤍": "White Heart",
  "🤎": "Brown Heart", "💔": "Broken Heart", "❤️‍🔥": "Fire Heart",
  "❣️": "Heart Mark", "💕": "Two Hearts", "💞": "Revolving Hearts",
  "💓": "Heartbeat", "💗": "Growing Heart", "💖": "Sparkling Heart",
  "💘": "Heart Arrow", "💝": "Heart Ribbon", "💟": "Heart Decor",
  "💯": "100", "✅": "Check", "❌": "Cross", "❗": "Exclamation", "❓": "Question",
  "💫": "Dizzy", "💥": "Boom", "💤": "Zzz", "🌀": "Cyclone",
  "♈": "Aries", "♉": "Taurus", "♊": "Gemini", "♋": "Cancer",
  "♌": "Leo", "♍": "Virgo", "♎": "Libra", "♏": "Scorpio",
  "♐": "Sagittarius", "♑": "Capricorn", "♒": "Aquarius", "♓": "Pisces",

  // Flags
  "🏁": "Checkered Flag", "🚩": "Red Flag", "🏳️": "White Flag",
  "🏳️‍🌈": "Pride", "🏳️‍⚧️": "Trans Pride", "🏴‍☠️": "Pirate",
  "🇺🇸": "USA", "🇬🇧": "UK", "🇨🇦": "Canada", "🇦🇺": "Australia",
  "🇩🇪": "Germany", "🇫🇷": "France", "🇪🇸": "Spain", "🇮🇹": "Italy",
  "🇯🇵": "Japan", "🇰🇷": "Korea", "🇨🇳": "China", "🇮🇳": "India",
  "🇧🇷": "Brazil", "🇲🇽": "Mexico", "🇿🇦": "South Africa",
  "🇳🇬": "Nigeria", "🇰🇪": "Kenya", "🇸🇦": "Saudi Arabia", "🇦🇪": "UAE",
  "🇮🇱": "Israel", "🇹🇷": "Turkey", "🇵🇰": "Pakistan",
  "🇮🇩": "Indonesia", "🇵🇭": "Philippines", "🇻🇳": "Vietnam",
  "🇹🇭": "Thailand", "🇸🇬": "Singapore", "🇳🇿": "New Zealand",
  "🇦🇷": "Argentina", "🇨🇴": "Colombia", "🇵🇱": "Poland", "🇺🇦": "Ukraine",
  "🇳🇱": "Netherlands", "🇸🇪": "Sweden", "🇳🇴": "Norway", "🇩🇰": "Denmark",
  "🇫🇮": "Finland", "🇮🇪": "Ireland", "🇵🇹": "Portugal", "🇬🇷": "Greece",
  "🇨🇭": "Switzerland", "🇷🇴": "Romania", "🇭🇷": "Croatia",
};

export function getEmojiName(emoji: string): string | null {
  return EMOJI_NAMES[emoji] || null;
}
