-- Icebreaker questions seed (curated)
-- Total: ~450 engaging, emoji-friendly questions across 20 categories
-- Each completes: "5 Emojis I would use to describe..."

INSERT INTO public.icebreaker_questions (question, category) VALUES

-- ═══ DAILY LIFE ═══
('my morning routine', 'daily_life'),
('my relationship with my alarm clock', 'daily_life'),
('my coffee addiction level', 'daily_life'),
('what my brain looks like at work', 'daily_life'),
('my cooking disaster stories', 'daily_life'),
('what happens when I''m hungry', 'daily_life'),
('my phone battery anxiety', 'daily_life'),
('my procrastination style', 'daily_life'),
('what my fridge contains right now', 'daily_life'),
('my social battery level', 'daily_life'),
('what I''m like before my first coffee', 'daily_life'),
('my weekend energy versus weekday energy', 'daily_life'),
('my ability to find matching socks', 'daily_life'),
('what my browser history reveals', 'daily_life'),
('my late night snack habits', 'daily_life'),
('what I do when the wifi is down', 'daily_life'),
('what my morning hair looks like', 'daily_life'),
('what I''m like when I''m running late', 'daily_life'),
('what happens when I try to be productive', 'daily_life'),
('my relationship with house plants', 'daily_life'),

-- ═══ FOOD & COOKING ═══
('my cooking skills', 'food_cooking'),
('what happens when I try baking', 'food_cooking'),
('my spice tolerance level', 'food_cooking'),
('my midnight snack habits', 'food_cooking'),
('what happens when I get hangry', 'food_cooking'),
('my relationship with takeout apps', 'food_cooking'),
('what my kitchen looks like after cooking', 'food_cooking'),
('my experience trying new cuisines', 'food_cooking'),
('what my ideal food truck would serve', 'food_cooking'),
('my relationship with dessert', 'food_cooking'),
('what my comfort food looks like', 'food_cooking'),
('my relationship with hot sauce', 'food_cooking'),
('what happens when I burn something', 'food_cooking'),
('what my signature dish would be', 'food_cooking'),
('what my dream kitchen would have', 'food_cooking'),
('my experience with potluck contributions', 'food_cooking'),
('my coffee brewing ritual', 'food_cooking'),
('what my go-to ingredients are', 'food_cooking'),
('my relationship with leftovers', 'food_cooking'),

-- ═══ TRAVEL & ADVENTURE ═══
('my ideal vacation destination', 'travel_adventure'),
('how I pack for trips', 'travel_adventure'),
('my airport survival strategy', 'travel_adventure'),
('my worst travel disaster', 'travel_adventure'),
('how I navigate new cities', 'travel_adventure'),
('my road trip snack game', 'travel_adventure'),
('my sense of direction', 'travel_adventure'),
('my hiking endurance level', 'travel_adventure'),
('my passport photo reality', 'travel_adventure'),
('my travel playlist vibe', 'travel_adventure'),
('my adventure sport courage', 'travel_adventure'),
('my camping experience level', 'travel_adventure'),
('my backpacking abilities', 'travel_adventure'),
('my travel bucket list vibe', 'travel_adventure'),
('my beach vacation energy', 'travel_adventure'),
('my foreign currency confusion', 'travel_adventure'),
('my tent setup skills', 'travel_adventure'),
('my local food courage level', 'travel_adventure'),
('my language skills abroad', 'travel_adventure'),

-- ═══ MUSIC ═══
('my music taste', 'music'),
('how I sound when I sing', 'music'),
('my car karaoke sessions', 'music'),
('how I dance when nobody''s watching', 'music'),
('my shower singing voice', 'music'),
('the last song stuck in my head', 'music'),
('my concert experience energy', 'music'),
('my air guitar abilities', 'music'),
('my guilty pleasure songs', 'music'),
('my karaoke song selection process', 'music'),
('how I react to my jam coming on', 'music'),
('my dancing at music festivals', 'music'),
('my drum skills on steering wheels', 'music'),
('my music from high school', 'music'),
('my dancing in grocery stores', 'music'),
('my relationship with vinyl records', 'music'),
('my headphone tangling situation', 'music'),

-- ═══ MOVIES & TV ═══
('my binge watching habits', 'movies_tv'),
('my reaction to cliffhangers', 'movies_tv'),
('my movie snack preferences', 'movies_tv'),
('how I watch horror movies', 'movies_tv'),
('my reality TV guilty pleasures', 'movies_tv'),
('my movie marathon endurance', 'movies_tv'),
('my reaction to plot twists', 'movies_tv'),
('my cartoon watching as an adult', 'movies_tv'),
('my Netflix queue right now', 'movies_tv'),
('how I react to jump scares', 'movies_tv'),
('my reaction to favorite character deaths', 'movies_tv'),
('my movie night preparation ritual', 'movies_tv'),
('my superhero movie opinions', 'movies_tv'),
('my binge watching recovery process', 'movies_tv'),
('my movie trivia knowledge', 'movies_tv'),

-- ═══ PERSONALITY ═══
('my energy levels throughout the day', 'personality_traits'),
('my reaction to surprises', 'personality_traits'),
('my morning personality versus evening personality', 'personality_traits'),
('how I am with directions', 'personality_traits'),
('my comfort zone boundaries', 'personality_traits'),
('how I am in awkward situations', 'personality_traits'),
('my spontaneity levels', 'personality_traits'),
('how I am when hangry', 'personality_traits'),
('my comfort level with karaoke', 'personality_traits'),
('my reaction to autocorrect fails', 'personality_traits'),
('how I handle compliments', 'personality_traits'),
('my organizational chaos', 'personality_traits'),
('my reaction to unexpected plans', 'personality_traits'),
('my multitasking reality versus expectations', 'personality_traits'),
('my patience when technology fails', 'personality_traits'),

-- ═══ HYPOTHETICALS ═══
('what I''d do with a million dollars', 'hypotheticals'),
('how I''d survive a zombie apocalypse', 'hypotheticals'),
('my life as a superhero', 'hypotheticals'),
('what I''d bring to a deserted island', 'hypotheticals'),
('my reaction to time travel being real', 'hypotheticals'),
('what I''d do if I could fly', 'hypotheticals'),
('my reaction to meeting my clone', 'hypotheticals'),
('what I''d do with invisible powers', 'hypotheticals'),
('my behavior in a haunted house', 'hypotheticals'),
('how I''d survive in the wilderness', 'hypotheticals'),
('what I''d do if animals could talk', 'hypotheticals'),
('my life as a cartoon character', 'hypotheticals'),
('what I''d do with three wishes', 'hypotheticals'),
('how I''d survive without my phone', 'hypotheticals'),
('what I''d bring to Mars', 'hypotheticals'),
('my life in a video game', 'hypotheticals'),
('how I''d handle being shrunk to ant size', 'hypotheticals'),
('my behavior in zero gravity', 'hypotheticals'),
('how I''d survive on a reality show', 'hypotheticals'),
('what I''d do if I could read minds', 'hypotheticals'),
('my life as a wizard', 'hypotheticals'),
('how I''d spend a day as someone else', 'hypotheticals'),
('what I''d do if I could shapeshift', 'hypotheticals'),
('what I''d do if I could breathe underwater', 'hypotheticals'),

-- ═══ CHILDHOOD NOSTALGIA ═══
('my childhood bedroom', 'childhood_nostalgia'),
('Saturday morning cartoons back then', 'childhood_nostalgia'),
('school lunch trading sessions', 'childhood_nostalgia'),
('childhood fears that seem silly now', 'childhood_nostalgia'),
('summer vacation as a kid', 'childhood_nostalgia'),
('my childhood Halloween costume game', 'childhood_nostalgia'),
('sleepovers at friends houses', 'childhood_nostalgia'),
('childhood birthday party expectations', 'childhood_nostalgia'),
('recess time energy levels', 'childhood_nostalgia'),
('snow day excitement levels', 'childhood_nostalgia'),
('childhood fort building expertise', 'childhood_nostalgia'),
('childhood ice cream truck chase speed', 'childhood_nostalgia'),
('my childhood pet situation', 'childhood_nostalgia'),
('childhood tooth fairy negotiations', 'childhood_nostalgia'),
('my childhood art masterpieces', 'childhood_nostalgia'),
('summer camp adventure spirit', 'childhood_nostalgia'),
('childhood pillow fort architecture skills', 'childhood_nostalgia'),
('my favorite childhood TV show obsession', 'childhood_nostalgia'),
('childhood allowance spending priorities', 'childhood_nostalgia'),
('my first bike riding experience', 'childhood_nostalgia'),

-- ═══ SOCIAL SITUATIONS ═══
('my energy at parties', 'social_situations'),
('meeting new people for the first time', 'social_situations'),
('my dance moves at weddings', 'social_situations'),
('my karaoke confidence', 'social_situations'),
('my reaction to surprise parties', 'social_situations'),
('being the only one who doesn''t know anyone', 'social_situations'),
('how I act in group photos', 'social_situations'),
('my energy after social events', 'social_situations'),
('running into someone I barely know', 'social_situations'),
('being asked to give a toast', 'social_situations'),
('my reaction to party games', 'social_situations'),
('how I handle meeting internet friends IRL', 'social_situations'),
('my reaction to themed costume parties', 'social_situations'),
('my small group vs large group energy', 'social_situations'),
('being introduced as the funny friend', 'social_situations'),
('how I act when everyone''s looking at me', 'social_situations'),

-- ═══ HOBBIES & INTERESTS ═══
('my relationship with houseplants', 'hobbies_interests'),
('my gaming setup at 2am', 'hobbies_interests'),
('my attempts at being crafty', 'hobbies_interests'),
('my dance moves when alone', 'hobbies_interests'),
('my reading pile versus reality', 'hobbies_interests'),
('my musical instrument graveyard', 'hobbies_interests'),
('my workout clothes to gym ratio', 'hobbies_interests'),
('my craft supply hoarding problem', 'hobbies_interests'),
('my podcast listening habits', 'hobbies_interests'),
('my attempts at morning yoga', 'hobbies_interests'),
('my plant parent anxiety levels', 'hobbies_interests'),
('how I collect random hobbies', 'hobbies_interests'),
('my gardening success rate', 'hobbies_interests'),
('my relationship with jigsaw puzzles', 'hobbies_interests'),
('my crafting skill versus ambition', 'hobbies_interests'),
('my cooking experiments gone wrong', 'hobbies_interests'),
('my reading nook setup', 'hobbies_interests'),
('my photography skills in reality', 'hobbies_interests'),
('my relationship with unfinished books', 'hobbies_interests'),

-- ═══ POP CULTURE ═══
('my relationship with social media', 'pop_culture'),
('my phone''s photo gallery', 'pop_culture'),
('my celebrity crush evolution', 'pop_culture'),
('my relationship with TikTok', 'pop_culture'),
('my TV show commitment issues', 'pop_culture'),
('my Netflix algorithm', 'pop_culture'),
('my relationship with memes', 'pop_culture'),
('my streaming queue chaos', 'pop_culture'),
('my TV show guilty pleasures', 'pop_culture'),
('my social media scroll behavior', 'pop_culture'),
('my thoughts on viral trends', 'pop_culture'),

-- ═══ EMOTIONS & VIBES ═══
('my energy on a Monday morning', 'emotions_vibes'),
('my vibe when it starts raining', 'emotions_vibes'),
('my mood after a good meal', 'emotions_vibes'),
('my vibe when I hear my favorite song', 'emotions_vibes'),
('my energy after three cups of coffee', 'emotions_vibes'),
('my vibe when someone cancels plans', 'emotions_vibes'),
('my mood when I find money in old jeans', 'emotions_vibes'),
('my energy during a thunderstorm', 'emotions_vibes'),
('my mood on a snow day', 'emotions_vibes'),
('my vibe at the beach', 'emotions_vibes'),
('my mood when packages arrive', 'emotions_vibes'),
('my energy around animals', 'emotions_vibes'),
('my vibe in bookstores', 'emotions_vibes'),
('my mood during Friday afternoons', 'emotions_vibes'),
('my energy when I''m home alone', 'emotions_vibes'),
('my vibe during vacation', 'emotions_vibes'),
('my mood when I accomplish something big', 'emotions_vibes'),
('my brain at 3am', 'emotions_vibes'),

-- ═══ WORK & PRODUCTIVITY ═══
('how I procrastinate before big deadlines', 'work_productivity'),
('my desk organization skills', 'work_productivity'),
('my brain during important meetings', 'work_productivity'),
('how productive I am after lunch', 'work_productivity'),
('my actual productivity versus my plans', 'work_productivity'),
('my workspace when nobody is watching', 'work_productivity'),
('my motivation on Friday afternoons', 'work_productivity'),
('my relationship with the snooze button', 'work_productivity'),
('how I handle creative blocks', 'work_productivity'),
('my energy when tackling my least favorite tasks', 'work_productivity'),
('my coffee consumption during work hours', 'work_productivity'),

-- ═══ SEASONS & WEATHER ═══
('what happens to my hair in humidity', 'seasons_weather'),
('my reaction to the first snow', 'seasons_weather'),
('my snow day personality', 'seasons_weather'),
('what spring cleaning does to me', 'seasons_weather'),
('my summer vacation expectations vs reality', 'seasons_weather'),
('my reaction to seasonal allergies', 'seasons_weather'),
('my relationship with hot chocolate weather', 'seasons_weather'),
('what my umbrella situation looks like', 'seasons_weather'),
('my reaction to perfect weather days', 'seasons_weather'),
('what happens when I forget sunscreen', 'seasons_weather'),
('how I dress for unpredictable weather', 'seasons_weather'),
('my winter morning routine', 'seasons_weather'),
('what happens to my motivation in winter', 'seasons_weather'),
('my reaction to surprise thunderstorms', 'seasons_weather'),

-- ═══ ANIMALS & NATURE ═══
('my spirit animal', 'animals_nature'),
('how I feel about spiders', 'animals_nature'),
('what I''d be as a zoo animal', 'animals_nature'),
('my green thumb abilities', 'animals_nature'),
('how I handle bug encounters', 'animals_nature'),
('what ocean creature represents me', 'animals_nature'),
('my pet''s personality in a nutshell', 'animals_nature'),
('what farm animal matches my energy', 'animals_nature'),
('my morning routine as a cat', 'animals_nature'),
('what kind of dog owner I am', 'animals_nature'),
('what safari animal I''d befriend first', 'animals_nature'),
('my reaction to unexpected animal encounters', 'animals_nature'),
('my stargazing attention span', 'animals_nature'),
('what type of flower represents my mood', 'animals_nature'),
('my reaction to animal videos online', 'animals_nature'),
('my survival skills in nature', 'animals_nature'),
('my beach day survival kit', 'animals_nature'),
('my picnic planning abilities', 'animals_nature'),

-- ═══ SPORTS & FITNESS ═══
('my gym playlist energy', 'sports_fitness'),
('my post-workout appearance', 'sports_fitness'),
('my reaction to leg day', 'sports_fitness'),
('how I look attempting yoga', 'sports_fitness'),
('my dance moves at the gym', 'sports_fitness'),
('my basketball shooting accuracy', 'sports_fitness'),
('my hiking stamina', 'sports_fitness'),
('my yoga poses versus reality', 'sports_fitness'),
('my sports coordination skills', 'sports_fitness'),
('my flexibility in real life', 'sports_fitness'),
('my marathon mentality', 'sports_fitness'),
('my swimming technique', 'sports_fitness'),
('how I motivate myself to work out', 'sports_fitness'),
('my golf swing reality', 'sports_fitness'),
('my workout outfit confidence', 'sports_fitness'),
('my fitness tracker relationship', 'sports_fitness'),

-- ═══ TECHNOLOGY ═══
('how I feel about autocorrect', 'technology'),
('my phone battery at 3pm', 'technology'),
('my reaction to software updates', 'technology'),
('my photo storage situation', 'technology'),
('my reaction to error messages', 'technology'),
('my phone''s camera roll', 'technology'),
('my reaction to low battery warnings', 'technology'),
('how I organize my apps', 'technology'),
('my WiFi connection at home', 'technology'),
('my typing speed on mobile', 'technology'),
('how I use dark mode', 'technology'),
('my computer when gaming', 'technology'),
('my relationship with notifications', 'technology'),

-- ═══ FASHION & STYLE ═══
('how I dress for grocery runs', 'fashion_style'),
('my shoe collection situation', 'fashion_style'),
('my closet organization skills', 'fashion_style'),
('my sock drawer reality', 'fashion_style'),
('my pajama game strength', 'fashion_style'),
('my sunglasses collection vibe', 'fashion_style'),
('my thrift store hunting skills', 'fashion_style'),
('how I dress when working from home', 'fashion_style'),
('my mirror selfie energy', 'fashion_style'),
('my outfit planning process', 'fashion_style'),
('my fashion risk taking level', 'fashion_style'),
('my laundry pile management', 'fashion_style'),
('my athletic wear lifestyle', 'fashion_style'),
('my shopping cart regrets', 'fashion_style'),

-- ═══ CITY LIFE ═══
('my morning commute experience', 'city_life'),
('my apartment''s size versus rent', 'city_life'),
('my walking speed on sidewalks', 'city_life'),
('my relationship with food trucks', 'city_life'),
('my corner bodega relationship', 'city_life'),
('navigating rush hour crowds', 'city_life'),
('my rooftop or balcony situation', 'city_life'),
('my late night food options', 'city_life'),
('finding green space nearby', 'city_life'),
('my local restaurant rotation', 'city_life'),
('my neighborhood pizza loyalty', 'city_life'),
('my relationship with parking spots', 'city_life'),
('dealing with apartment hunting', 'city_life'),
('my local happy hour spots', 'city_life'),
('navigating the subway system', 'city_life'),

-- ═══ DREAMS & GOALS ═══
('my dream job as a kid', 'dreams_goals'),
('what success looks like to me', 'dreams_goals'),
('my retirement fantasy', 'dreams_goals'),
('my dream vacation destination', 'dreams_goals'),
('my secret creative ambition', 'dreams_goals'),
('what motivates me every morning', 'dreams_goals'),
('my ideal living situation', 'dreams_goals'),
('the skill I most want to master', 'dreams_goals'),
('my dream dinner party guest list', 'dreams_goals'),
('my biggest bucket list item', 'dreams_goals'),
('my dream side hustle', 'dreams_goals'),
('my vision of perfect work life balance', 'dreams_goals'),
('the adventure I dream about most', 'dreams_goals'),
('my vision of a perfect day', 'dreams_goals'),
('my dream collaboration', 'dreams_goals'),
('the goal that scares me most', 'dreams_goals'),
('my vision of true happiness', 'dreams_goals'),
('the tradition I want to start', 'dreams_goals');
